"""add_user_profile_fields

Revision ID: 06211e21653f
Revises: 1c5ba76e5202
Create Date: 2025-07-30 14:32:02.741742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06211e21653f'
down_revision: Union[str, None] = '1c5ba76e5202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Profile Information
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('favorite_location', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('is_public_profile', sa.Boolean(), nullable=False, server_default='false'))
    
    # Notification Preferences
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('gift_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('marketing_emails', sa.Boolean(), nullable=False, server_default='false'))
    
    # Achievement Tracking
    op.add_column('users', sa.Column('total_gifts_created', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('total_gifts_claimed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('total_chains_created', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('first_gift_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_gift_claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'first_gift_claimed_at')
    op.drop_column('users', 'first_gift_created_at')
    op.drop_column('users', 'total_chains_created')
    op.drop_column('users', 'total_gifts_claimed')
    op.drop_column('users', 'total_gifts_created')
    op.drop_column('users', 'marketing_emails')
    op.drop_column('users', 'gift_notifications')
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'is_public_profile')
    op.drop_column('users', 'favorite_location')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
