"""Add gift chain tables

Revision ID: 3a20bec99e51
Revises: 7e3dc18027ad
Create Date: 2025-07-29 09:22:33.358580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a20bec99e51'
down_revision: Union[str, None] = '7e3dc18027ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED', name='chainstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creation_tx_hash', sa.String(), nullable=False),
    sa.Column('creation_block_number', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_gift_chains_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gift_chains'))
    )
    op.create_index(op.f('ix_gift_chains_chain_id'), 'gift_chains', ['chain_id'], unique=True)
    op.create_table('chain_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('unlock_type', sa.Enum('GPS', 'VIDEO', 'IMAGE', 'MARKDOWN', 'QUIZ', 'PASSWORD', 'URL', name='unlocktype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('unlock_data', sa.JSON(), nullable=True),
    sa.Column('clue_hash', sa.String(), nullable=False),
    sa.Column('reward_amount', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['gift_chains.id'], name=op.f('fk_chain_steps_chain_id_gift_chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_steps'))
    )
    op.create_table('chain_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('claimer_address', sa.String(), nullable=False),
    sa.Column('claim_lat', sa.Float(), nullable=True),
    sa.Column('claim_lng', sa.Float(), nullable=True),
    sa.Column('claim_data', sa.JSON(), nullable=True),
    sa.Column('claim_tx_hash', sa.String(), nullable=False),
    sa.Column('claim_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['gift_chains.id'], name=op.f('fk_chain_claims_chain_id_gift_chains')),
    sa.ForeignKeyConstraint(['step_id'], ['chain_steps.id'], name=op.f('fk_chain_claims_step_id_chain_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_claims'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_claims')
    op.drop_table('chain_steps')
    op.drop_index(op.f('ix_gift_chains_chain_id'), table_name='gift_chains')
    op.drop_table('gift_chains')
    # ### end Alembic commands ###
