"""add_unlock_types_to_gifts

Revision ID: 41c9bea25a8b
Revises: 4ae3b7aae5ee
Create Date: 2025-07-29 19:46:01.842770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c9bea25a8b'
down_revision: Union[str, None] = '4ae3b7aae5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
