"""add_completed_at_and_created_at_to_chain_steps

Revision ID: 4ae3b7aae5ee
Revises: 73e4f9f8fcdb
Create Date: 2025-07-29 14:21:30.864415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae3b7aae5ee'
down_revision: Union[str, None] = '73e4f9f8fcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_steps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chain_steps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_steps', 'created_at')
    op.drop_column('chain_steps', 'completed_at')
    # ### end Alembic commands ###
