"""update_chain_step_model_for_api_compatibility

Revision ID: 73e4f9f8fcdb
Revises: dcf53d58ad5e
Create Date: 2025-07-29 14:16:47.010672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e4f9f8fcdb'
down_revision: Union[str, None] = 'dcf53d58ad5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_steps', sa.Column('step_title', sa.String(), nullable=False))
    op.add_column('chain_steps', sa.Column('step_message', sa.Text(), nullable=True))
    op.add_column('chain_steps', sa.Column('step_value', sa.String(), nullable=False))
    op.alter_column('chain_steps', 'clue_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chain_steps', 'title')
    op.drop_column('chain_steps', 'message')
    op.drop_column('chain_steps', 'reward_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_steps', sa.Column('reward_amount', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chain_steps', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chain_steps', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('chain_steps', 'clue_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chain_steps', 'step_value')
    op.drop_column('chain_steps', 'step_message')
    op.drop_column('chain_steps', 'step_title')
    # ### end Alembic commands ###
