"""add_unlock_type_fields

Revision ID: 7cb8bc4d67df
Revises: 41c9bea25a8b
Create Date: 2025-07-29 19:47:21.891588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb8bc4d67df'
down_revision: Union[str, None] = '41c9bea25a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('unlock_type', sa.Enum('GPS', 'URL', 'MESSAGE', name='unlocktype'), nullable=False, server_default='GPS'))
    op.add_column('gifts', sa.Column('unlock_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts', 'unlock_data')
    op.drop_column('gifts', 'unlock_type')
    # ### end Alembic commands ###
