"""add_bonus_reward_fields_to_chain_steps

Revision ID: a1e9ade6068d
Revises: c9fe5f64494d
Create Date: 2025-07-29 21:15:50.677185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e9ade6068d'
down_revision: Union[str, None] = 'c9fe5f64494d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
