"""update_gift_chain_model_for_api_compatibility

Revision ID: dcf53d58ad5e
Revises: 3a20bec99e51
Create Date: 2025-07-29 14:04:13.739330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf53d58ad5e'
down_revision: Union[str, None] = '3a20bec99e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_chains', sa.Column('giver_address', sa.String(), nullable=False))
    op.add_column('gift_chains', sa.Column('recipient_email', sa.String(), nullable=True))
    op.add_column('gift_chains', sa.Column('chain_title', sa.String(), nullable=False))
    op.add_column('gift_chains', sa.Column('chain_description', sa.Text(), nullable=True))
    op.add_column('gift_chains', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('gift_chains', sa.Column('is_expired', sa.Boolean(), nullable=False))
    op.add_column('gift_chains', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('gift_chains', sa.Column('blockchain_chain_id', sa.BigInteger(), nullable=True))
    op.add_column('gift_chains', sa.Column('transaction_hash', sa.String(), nullable=True))
    op.add_column('gift_chains', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('gift_chains', 'description')
    op.drop_column('gift_chains', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_chains', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('gift_chains', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('gift_chains', 'completed_at')
    op.drop_column('gift_chains', 'transaction_hash')
    op.drop_column('gift_chains', 'blockchain_chain_id')
    op.drop_column('gift_chains', 'expiry_date')
    op.drop_column('gift_chains', 'is_expired')
    op.drop_column('gift_chains', 'is_completed')
    op.drop_column('gift_chains', 'chain_description')
    op.drop_column('gift_chains', 'chain_title')
    op.drop_column('gift_chains', 'recipient_email')
    op.drop_column('gift_chains', 'giver_address')
    # ### end Alembic commands ###
