"""create_tables_for_neon

Revision ID: f1e739be8fe4
Revises: 06211e21653f
Create Date: 2025-08-01 10:07:11.790297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e739be8fe4'
down_revision: Union[str, None] = '06211e21653f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('favorite_location', sa.String(length=200), nullable=True),
    sa.Column('is_public_profile', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('gift_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('total_gifts_created', sa.Integer(), nullable=False),
    sa.Column('total_gifts_claimed', sa.Integer(), nullable=False),
    sa.Column('total_chains_created', sa.Integer(), nullable=False),
    sa.Column('first_gift_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_gift_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('gift_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('giver_address', sa.String(), nullable=False),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('chain_title', sa.String(), nullable=False),
    sa.Column('chain_description', sa.Text(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED', name='chainstatus'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creation_tx_hash', sa.String(), nullable=False),
    sa.Column('creation_block_number', sa.BigInteger(), nullable=True),
    sa.Column('blockchain_chain_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_gift_chains_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gift_chains'))
    )
    op.create_index(op.f('ix_gift_chains_chain_id'), 'gift_chains', ['chain_id'], unique=True)
    op.create_table('gifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('escrow_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'EXPIRED', name='giftstatus'), nullable=False),
    sa.Column('unlock_type', sa.Enum('GPS', 'VIDEO', 'IMAGE', 'MARKDOWN', 'QUIZ', 'PASSWORD', 'URL', name='unlocktype'), nullable=False),
    sa.Column('unlock_challenge_data', sa.Text(), nullable=True),
    sa.Column('reward_content', sa.Text(), nullable=True),
    sa.Column('reward_content_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_gifts_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gifts'))
    )
    op.create_index(op.f('ix_gifts_escrow_id'), 'gifts', ['escrow_id'], unique=True)
    op.create_table('chain_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_title', sa.String(), nullable=False),
    sa.Column('step_message', sa.Text(), nullable=True),
    sa.Column('unlock_type', sa.Enum('GPS', 'VIDEO', 'IMAGE', 'MARKDOWN', 'QUIZ', 'PASSWORD', 'URL', name='unlocktype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('unlock_data', sa.JSON(), nullable=True),
    sa.Column('clue_hash', sa.String(), nullable=True),
    sa.Column('step_value', sa.String(), nullable=False),
    sa.Column('reward_content', sa.Text(), nullable=True),
    sa.Column('reward_content_type', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_unlocked', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['gift_chains.id'], name=op.f('fk_chain_steps_chain_id_gift_chains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_steps'))
    )
    op.create_table('chain_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('claimer_address', sa.String(), nullable=False),
    sa.Column('claim_lat', sa.Float(), nullable=True),
    sa.Column('claim_lng', sa.Float(), nullable=True),
    sa.Column('claim_data', sa.JSON(), nullable=True),
    sa.Column('claim_tx_hash', sa.String(), nullable=False),
    sa.Column('claim_block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['gift_chains.id'], name=op.f('fk_chain_claims_chain_id_gift_chains')),
    sa.ForeignKeyConstraint(['step_id'], ['chain_steps.id'], name=op.f('fk_chain_claims_step_id_chain_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_claims'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chain_claims')
    op.drop_table('chain_steps')
    op.drop_index(op.f('ix_gifts_escrow_id'), table_name='gifts')
    op.drop_table('gifts')
    op.drop_index(op.f('ix_gift_chains_chain_id'), table_name='gift_chains')
    op.drop_table('gift_chains')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
