"""add_reward_content_fields_to_chain_steps_v2

Revision ID: f8587d96fe1b
Revises: a1e9ade6068d
Create Date: 2025-07-29 21:17:04.788330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8587d96fe1b'
down_revision: Union[str, None] = 'a1e9ade6068d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chain_steps', sa.Column('reward_content', sa.Text(), nullable=True))
    op.add_column('chain_steps', sa.Column('reward_content_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chain_steps', 'reward_content_type')
    op.drop_column('chain_steps', 'reward_content')
    # ### end Alembic commands ###
